# Generated by Django 2.2.4 on 2019-09-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190918_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
